// <auto-generated />
using System;
using Investments.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Investments.Persistence.Migrations
{
    [DbContext(typeof(InvestmentsContext))]
    [Migration("20220831010130_withdrawnIdColumnFunds")]
    partial class withdrawnIdColumnFunds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Investments.Domain.Models.DetailedFunds", b =>
                {
                    b.Property<string>("Papel")
                        .HasColumnType("TEXT");

                    b.Property<double>("AluguelPorM2")
                        .HasColumnType("REAL");

                    b.Property<double>("CapRate")
                        .HasColumnType("REAL");

                    b.Property<double>("Cotacao")
                        .HasColumnType("REAL");

                    b.Property<double>("DividendYield")
                        .HasColumnType("REAL");

                    b.Property<double>("FFOYield")
                        .HasColumnType("REAL");

                    b.Property<double>("Liquidez")
                        .HasColumnType("REAL");

                    b.Property<double>("PVP")
                        .HasColumnType("REAL");

                    b.Property<double>("PrecoDoM2")
                        .HasColumnType("REAL");

                    b.Property<double>("QtdDeImoveis")
                        .HasColumnType("REAL");

                    b.Property<string>("Segmento")
                        .HasColumnType("TEXT");

                    b.Property<double>("VacanciaMedia")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorDeMercado")
                        .HasColumnType("REAL");

                    b.HasKey("Papel");

                    b.ToTable("DetailedFunds");
                });

            modelBuilder.Entity("Investments.Domain.Models.Funds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Papel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Funds");
                });

            modelBuilder.Entity("Investments.Domain.Models.FundsYeld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Papel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltDataCom")
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("FundsYeld");
                });
#pragma warning restore 612, 618
        }
    }
}
